<?php
$reactAppUrl = $this->getReactAppUrl();
$manifestJson = file_get_contents($reactAppUrl . '/manifest.json');
$manifest = json_decode($manifestJson, true);
?>

<style type="text/css">
    .main-container {
        padding: 0 !important;
    }
</style>

<link rel="stylesheet" href="<?php echo $reactAppUrl . $manifest['main.css']; ?>" />
<div id="root"></div>

<script src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
<script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>

<script src="<?php echo $reactAppUrl . $manifest['vendors.js']; ?>"></script>
<script src="<?php echo $reactAppUrl . $manifest['main.js']; ?>"></script>

<script>
document.addEventListener('DOMContentLoaded', function() {
    console.log('DOM chargé');
    var rootElement = document.getElementById('root');
    console.log('Élément root:', rootElement);
    
    if (rootElement) {
        console.log('Application React chargée');
    } else {
        console.error("Élément 'root' non trouvé");
    }
});
</script>