<?php
    // Get API response
    $apiHelper = Mage::helper('contestio_connect/api');
    $response = $apiHelper->callApi('/org/header', 'GET');
    
    $navButtons = $response['buttons'];
?>

<div id="contestio_wrapper" style="display: none;">
    <div
        id="contestio-header"
        class="contestio-btn-section"
        data-firstname="<?= $firstname ?>"
        data-pseudo="<?= $pseudo ?>"
    >
        <p id="contestio-header-text">
            <?php if ($pseudo): ?>
                Bonjour <span><?= $pseudo ?></span> 👋
            <?php endif; ?>
        </p>

        <ul>
            <?php foreach ($navButtons as $button) : ?>
            <!-- Print custom button styles -->
            <style>
                /* Default */
                <?php if (isset($button['styles'])): ?>
                a#<?= $button['slug'] ?> {
                    <?php echo $button['styles']; ?>
                }
                <?php endif; ?>

                /* Hover */
                <?php if (isset($button['hover'])): ?>
                a#<?= $button['slug'] ?>:hover,
                a#<?= $button['slug'] ?>.active {
                    <?php echo $button['hover']; ?>
                }
                <?php endif; ?>

                /* Focus and active */
                <?php if (isset($button['focus'])): ?>
                a#<?= $button['slug'] ?>:focus,
                a#<?= $button['slug'] ?>:active {
                    <?php echo $button['focus']; ?>
                }
                <?php endif; ?>
            </style>

            <?php
                $url = $this->getUrl('contestio/accueil');
                $isActive = strpos($currentPageUrl, $this->getUrl('contestio/accueil')) === 0;

                // Détermine l'URL à utiliser
                if ($button['navUrl'] === 'contest') {
                $url = $this->getUrl('contestio/concours');
                $isActive = strpos($currentPageUrl, $this->getUrl('contestio/concours')) === 0;
                } elseif ($button['navUrl'] === 'survey') {
                $url = $this->getUrl('contestio/sondage');
                $isActive = strpos($currentPageUrl, $this->getUrl('contestio/sondage')) === 0;
                }
            ?>

            <a
                id="<?= $button['slug'] ?>"
                href="<?= $url ?>"
                class="basic-button <?= $isActive ? 'active' : '' ?>"
            >
                <?= $button['text'] ?>
            </a>
            <?php endforeach; ?>
        </ul>
    </div>

    <h1>Contestio</h1>
    <p>Plugin Magento 1.9</p>
</div>