<?php
$iframeUrl = $this->getIframeUrl();
$queryParams = $this->getQueryParams();
?>

<style>
  /* Enlarge the container */
  .main-container {
    max-width: 100% !important;
    padding: 0 !important;
    margin: 0 !important;
  }

  /* Contestio container */
  .contestio-container {
    width: 100%;
    height: 100vh;
  }

  /* Contestio iframe */
  .contestio-iframe {
    width: 100%;
    height: 100%;
    border: none;
  }
</style>

<div class="contestio-container">
  <iframe
    src="<?php echo $iframeUrl; ?><?php echo $queryParams; ?>"
    width="100%"
    height="100%"
    frameborder="0"
    allowfullscreen
    class="contestio-iframe">
  </iframe>
</div>
