<?php
$reactAppUrl = $this->getReactAppUrl();
$iframeUrl = $this->getIframeUrl();
$queryParams = $this->getQueryParams();

// $manifest = null;

// try {
//   // Get manifest.json from remote server
//   $curl = curl_init($reactAppUrl . '/manifest.json' . '?v=' . time());
//   curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
//   $response = curl_exec($curl);
//   curl_close($curl);
  
//   $manifest = json_decode($response, true);
// } catch (Exception $e) {
//   $manifest = null;
// }
?>

<style>
  /* Enlarge the container */
  .main-container {
    max-width: 100% !important;
    padding: 0 !important;
    margin: 0 !important;
  }
</style>

<div class="contestio-container">
  <iframe
    src="<?php echo $iframeUrl; ?><?php echo $queryParams; ?>"
    width="100%"
    height="100%"
    frameborder="0"
    allowfullscreen
    class="contestio-iframe">
  </iframe>
</div>
